language: julia
os:
  - linux
julia:
  - 0.3
  # - 0.4  # fails
  # - 0.5  # fails
notifications:
  email: spencer.f.russell@gmail.com
sudo: true
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.add("BinDeps"); Pkg.checkout("BinDeps")' # latest master needed for Pacman support
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("AudioIO"); Pkg.test("AudioIO"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("AudioIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
